paginate: 5
name: Jiaaro
description: Jiaaro (on life, the universe, and everything)
url: http://www.jiaaro.com
permalink: /:title
highlighter: rogue
markdown: kramdown
gems: 
  - jekyll-paginate
  - jekyll-redirect-from
kramdown:
  input: GFM
